// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Transaction struct {
	ID       int64
	Uid      string
	Created  time.Time
	Amount   string
	Currency string
}
