// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Transaction struct {
	ID       int32
	Uid      string
	Created  time.Time
	Amount   string
	Currency string
	UserID   sql.NullInt32
}
